config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('homework.urls', namespace='homework')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homework/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import ProductListView, ProductDetailView, ProductCreateView, NoteListView, NoteUpdateView, \
    NoteDetailView, NoteCreateView, NoteDeleteView, ContactsTemplateView, ProductUpdateView, ProductDeleteView

app_name = 'homework'

urlpatterns = [
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('product_update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('', ProductListView.as_view(), name='index'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('blog/', NoteListView.as_view(), name='blog'),
    path('update_note/<slug:slug>/', NoteUpdateView.as_view(), name='update_note'),
    path('create_note/', NoteCreateView.as_view(), name='create_note'),
    path('note_delete/<slug:slug>/', NoteDeleteView.as_view(), name='note_delete'),
    path('note_detail/<slug:slug>/', NoteDetailView.as_view(), name='note_detail'),
]

homework/models.py
import uuid
from django.utils.text import slugify
from django.db import models
# Create your models here.


NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name_product = models.CharField(max_length=20, verbose_name='имя')
    description = models.CharField(max_length=150, verbose_name='описание')
    preview = models.ImageField(upload_to='product/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    price = models.IntegerField(verbose_name='цена')
    made = models.DateField(verbose_name='изготовлено', auto_now_add=True)
    change = models.DateField(verbose_name='изменено', auto_now=True)

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.pk} {self.name_product} {self.price} {self.category}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Category(models.Model):
    name_category = models.CharField(max_length=20, verbose_name='имя')
    description = models.CharField(max_length=150, verbose_name='описание')

    def __str__(self):
        return f'{self.pk} {self.name_category}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Note(models.Model):
    name = models.CharField(max_length=70, verbose_name='заголовок')
    slug = models.CharField(max_length=255, verbose_name='слаг', unique_for_date='made')
    the_text = models.CharField(max_length=200, verbose_name='текст')
    image = models.ImageField(upload_to='blog/', verbose_name='изображение', null=True)
    made = models.DateField(verbose_name='изготовлено', auto_now_add=True)
    published = models.BooleanField(verbose_name='опубликовано', default=False)
    views = models.PositiveIntegerField(verbose_name='просмотры', default=0)

    def views_up(self):
        self.views += 1

    def __str__(self):
        return f'Статья: {self.name}'

    def save(self, *args, **kwargs):
        if not self.slug:
            title = str(self.name)
            string = title.translate(
                str.maketrans("абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
                              "abvgdeejzijklmnoprstufhzcss_y_euaABVGDEEJZIJKLMNOPRSTUFHZCSS_Y_EUA"))
            self.slug = slugify(string)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'публикации'
        ordering = ('-made',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт', related_name='version')
    version_number = models.PositiveIntegerField(verbose_name='Номер версии', null=False, blank=False)
    version_name = models.CharField(max_length=50, verbose_name='Имя версии', null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name='Признак версии')

    def __str__(self):
        return f'{self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('version_number',)

homework/forms.py
from django import forms
from homework.models import Product, Version

STOP_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


def check_words(data):
    for word in STOP_WORDS:
        if word in data:
            raise forms.ValidationError(f'Недопустимое слово: {word}')


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data['name_product']
        check_words(name)
        description = cleaned_data['description']
        check_words(description)
        return cleaned_data

# class VersionForms(forms.ModelForm):
    # class Meta:
       #  model = Version
       #  field = '__all__'


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def clean_is_active(self):
        is_active = self.cleaned_data['is_active']
        product = self.cleaned_data['product']
        if is_active:
            Version.objects.filter(product=product).exclude(id=self.instance.id).update(is_active=False)
        return is_active

homework/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic
from homework.models import Product, Note
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, FormView, UpdateView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from .forms import ProductForm, VersionForm
from homework.models import Product, Version
from django.forms import inlineformset_factory


class ProductListView(generic.ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Список товаров'
        return context_data
# Create your views here.


class ProductDetailView(generic.DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']
        return context_data


class ProductCreateView(generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('homework:index')
    extra_context = {
        'title': 'Создание продукта'
    }


class ProductDeleteView(generic.DeleteView):
    model = Product
    success_url = reverse_lazy('homework:index')


class ContactsTemplateView(generic.TemplateView):
    template_name = 'homework/contacts2.html'


#class NoteCreateView(generic.CreateView):
#    model = Note
#    fields = ('name', 'the_text', 'image', 'published')
#    success_url = reverse_lazy('homework:blog')


class NoteDetailView(generic.DetailView):
    model = Note

    def get_object(self, queryset=None):
        note = super().get_object()
        note.views_up()
        return note

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Просмотр статьи'
        return context_data


class NoteListView(generic.ListView):
    model = Note


class NoteUpdateView(generic.UpdateView):
    model = Note
    fields = ('name', 'the_text', 'image', 'published')
    extra_context = {
        'title': 'изменить статью'
    }

    def get_success_url(self):
        return reverse('homework:note_detail', args=[*self.kwargs.values()])


class NoteCreateView(generic.CreateView):
    model = Note
    fields = ('name', 'the_text', 'image', 'published')
    success_url = reverse_lazy('homework:blog')
    extra_context = {
        'title': 'Создание статьи'
    }


class NoteDeleteView(generic.DeleteView):
    model = Note
    success_url = reverse_lazy('homework:blog')


class ProductUpdateView(generic.UpdateView):
    model = Product
    form_class = ProductForm
    extra_context = {
        'title': 'Изменение продукта'
    }
    success_url = reverse_lazy("homework:index")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        version_formset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        context_data['formset'] = version_formset()

        if self.request.method == 'POST':
            context_data['formset'] = version_formset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = version_formset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

homework/templates/homework/card.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

homework/templates/homework/contacts.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

homework/templates/homework/contacts2.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

homework/templates/homework/note_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

    <div class="container text-primary">
        <div class="row justify-content-md-center">
            <h1>Удалить статью</h1>
        </div>
    </div>

    <br>
    <div class="container">
        <div class="row justify-content-center">
            <form method="POST" , enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <h4><p class="text text-danger"> {{ object }}</h4>
                <br>
                Подтвердите удаление
                <input type="submit" class="btn-danger" value="Подтверждаю">
            </form>
        </div>
    </div>

{% endblock %}

homework/templates/homework/note_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
  <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.made }} руб.</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.the_text }}</li>
                        <li>- {{ object.slug }}</li>
                        <li>- опубликовано {{ object.made }}</li>
                        <li>- {{ object.published }}</li>
                        <li>- количество просмотров {{ object.views }}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
      <!-- Исходный вариант -->
        <!--<img src="/media/{{ object.preview }}" /> -->
        <img src="{% media_path object.image %}" />
  </div>
{% endblock %}

homework/templates/homework/note_form.html
{% extends 'base.html' %}
{% block content %}

    <br>
    <div class="container">
        <div class="row justify-content-center">
            <form method="POST" , enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Сохранить">
            </form>
        </div>
    </div>

{% endblock %}

homework/templates/homework/note_list.html
{% extends 'base.html' %}
{% block content %}
<a class="p-2 btn btn-outline-primary" href="{% url 'homework:create_note' %}">Создать</a>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.the_text }}</h1>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'homework:note_detail' object.slug %}">Подробнее</a>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'homework:note_delete' object.slug %}">Удалить</a>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'homework:update_note' object.slug %}">Изменить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

homework/templates/homework/product_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="col-6" xmlns="http://www.w3.org/1999/html">
    <div class="card">
        <div class="card-header"></div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            {{ object }}
            <button type="submit" class="btn btn-primary">Удалить</button>
          </form>
          <a class="btn btn-primary" href="{% url 'homework:index' %}">Назад</a>
        </div>
    </div>
</div>


{% endblock %}

homework/templates/homework/product_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
  <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name_product }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.description }}</li>
                        <li>- {{ object.category }}</li>
                        <li>- {{ object.made }}</li>
                        <li>- {{ object.change }}</li>
                        <p class="card-text">Категория: {{ object.category }}</p>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
      <!-- Исходный вариант -->
        <!--<img src="/media/{{ object.preview }}" /> -->
        <img src="{% media_path object.preview %}" />
        <img src="{{ object.preview|mediapath }}" />
  </div>
{% endblock %}

homework/templates/homework/product_form.html
{% extends 'base.html' %}
{% block content %}

<form class="row" method="POST" enctype="application/x-www-form-urlencoded">
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </div>
    </div>
    {% if object %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Версии продукта
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset %}
                        {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
</form>


{% endblock %}

homework/templates/homework/product_list.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'homework:create' %}" class ="btn btn-primary">Создать продукт</a>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name_product }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                    {% for version in object.version.all %}
                        <p class="card-text">{% if version.is_active %}Активная версия: {{ version }} {% endif %}</p>
                    {% endfor %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'homework:detail' object.pk %}">Подробнее</a>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'homework:product_update' object.pk %}">Изменить</a>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'homework:product_delete' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>